version: '1.0'
stages:
  - build
  - test
  - push
steps:

  BuildingDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: flask-image
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
    metadata:
      set:
        - CF_QUALITY: true
        - progress: 80%
        - url: http://<script>alert(1)</script>

  MyUnitTests: 
    title: Running Unit tests 
    stage: test 
    image: ${{BuildingDockerImage}} 
    commands:
      - python setup.py test
